#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }
Database.load_structure


if ARGV.length.nonzero?
  puts "Please try again without any arguments...\n" +
       "Try \"./serial_parser_storage\"\n"
  exit
end

loop do
  choose do |menu|
    menu.prompt = ""
    menu.choice('Start a session') do
      Reading.record(time: 1)
    end
    menu.choice('Query a session') do
      say(Table.new.generate(pressure_value: 62))
      exit
    end
    menu.choice('Exit') do
      exit
    end
  end
end
