#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

# if ARGV.size == 1 and ARGV[0] == "manage"
#   loop do
#     choose do |menu|
#       menu.prompt = ""

#       menu.choice('Add a scenario') do
#         user_input = ask("What scenario would you like to add?")
#         response = scenarios_controller.add(user_input)
#         say(response) unless response.nil?
#       end
#       menu.choice('List all scenarios') do
#         say(scenarios_controller.index)
#         exit
#       end
#       menu.choice('Exit') do
#         say("Peace Out!\n")
#         exit
#       end
#     end
#   end
# else
#   puts "[Help] Run as: ./serial_parser_storage manage"
# end
